### ISSUE TITLE
error cocurent logging

### ISSUE THREAD

**Issue by serazoli** [rverst/zgelf#2]
```
panic: runtime error: index out of range [1] with length 1

goroutine 1309 [running]:
github.com/rverst/zgelf.(*logBuffer).Copy(...)
        /home/*****/go/pkg/mod/github.com/rverst/zgelf@v0.0.0-20200728153303-fccb02ec5899/buffer.go:32
github.com/rverst/zgelf.(*GelfWriter).Flush(0xc000190700, 0x0)
        /home/*****/go/pkg/mod/github.com/rverst/zgelf@v0.0.0-20200728153303-fccb02ec5899/zgelf.go:128 +0x32d
github.com/rverst/zgelf.(*GelfWriter).bufferEvent(0xc000190700, 0xc00b442c60?)
        /home/*****/go/pkg/mod/github.com/rverst/zgelf@v0.0.0-20200728153303-fccb02ec5899/zgelf.go:220 +0x15e
github.com/rverst/zgelf.(*GelfWriter).process(0xc000190700, 0xc00b442c30)
        /home/*****/go/pkg/mod/github.com/rverst/zgelf@v0.0.0-20200728153303-fccb02ec5899/zgelf.go:208 +0x76a
github.com/rverst/zgelf.(*GelfWriter).worker.func1(0xc0007befb8?)
        /home/*****/go/pkg/mod/github.com/rverst/zgelf@v0.0.0-20200728153303-fccb02ec5899/zgelf.go:160 +0x65
created by github.com/rverst/zgelf.(*GelfWriter).worker
        /home/*****/go/pkg/mod/github.com/rverst/zgelf@v0.0.0-20200728153303-fccb02ec5899/zgelf.go:158 +0x36
```
this patch may fix the error:

```diff
Index: buffer.go
<+>UTF-8
===================================================================
diff --git a/buffer.go b/buffer.go
--- a/buffer.go	(revision fccb02ec5899f90ca1583e7ff9ed49e5a10b1adf)
+++ b/buffer.go	(date 1655975317137)
@@ -2,11 +2,13 @@
 
 import (
 	"fmt"
+	"sync"
 )
 
 type logBuffer struct {
-	buffers   [][]byte
-	size      int
+	buffers [][]byte
+	size    int
+	mu      sync.RWMutex
 }
 
 func NewLogBuffer() *logBuffer {
@@ -17,16 +19,22 @@
 }
 
 func (b *logBuffer) Add(data []byte) {
+	b.mu.Lock()
+	defer b.mu.Unlock()
 	b.size = b.size + len(data)
 	b.buffers = append(b.buffers, data)
 }
 
 func (b *logBuffer) Clear() {
+	b.mu.Lock()
+	defer b.mu.Unlock()
 	b.size = 0
 	b.buffers = make([][]byte, 0)
 }
 
 func (b *logBuffer) Copy() *logBuffer {
+	b.mu.RLock()
+	defer b.mu.RUnlock()
 	c := make([][]byte, len(b.buffers))
 	for i, x := range b.buffers {
 		c[i] = make([]byte, len(x))
@@ -43,6 +51,8 @@
 	if len(b.buffers) == 0 {
 		return nil, fmt.Errorf("no element left in buffer")
 	}
+	b.mu.Lock()
+	defer b.mu.Unlock()
 	r := b.buffers[:1]
 	b.buffers = b.buffers[1:]
 	b.size -= len(r[0])
Index: zgelf.go
<+>UTF-8
===================================================================
diff --git a/zgelf.go b/zgelf.go
--- a/zgelf.go	(revision fccb02ec5899f90ca1583e7ff9ed49e5a10b1adf)
+++ b/zgelf.go	(date 1656333047977)
@@ -39,7 +39,6 @@
 	queue       chan map[string]interface{}
 	wgProcess   sync.WaitGroup
 	wgFlush     sync.WaitGroup
-	mu          sync.RWMutex
 	buffer      *logBuffer
 	ticker      *time.Ticker
 }
@@ -122,9 +121,6 @@
 		return
 	}
 
-	w.mu.Lock()
-	defer w.mu.Unlock()
-
 	c := w.buffer.Copy()
 	w.buffer.Clear()
 



```

**Comment by rverst** [comment]
Yep, it could be like that. The module is no longer in use with me, I had used it 2 years ago for a project, but it never came to life...
I have patched this anyway, maybe it helps someone else.
